### ISSUE TITLE
引述块样式问题

### ISSUE THREAD

**Issue by TracyIverson** [zqhjl/Rem-Craft#11]
1. 在引述块内输入列表，前面的竖线丢失
![image](https://user-images.githubusercontent.com/27794098/159828753-12b06fb7-f55f-4fa5-8ec4-553eae1d6e44.png)
2.引述块内硬换行，竖线能否不留空隙
![image](https://user-images.githubusercontent.com/27794098/159829132-524fb09b-4acf-4c96-bd08-346c0df31554.png)

**Comment by zqhjl** [comment]
1. 我没能复现，会不会是竖线太淡了没看清
2. 已解决

**Comment by zqhjl** [comment]
1.问题已解决

**Comment by TracyIverson** [comment]
> 1. 我没能复现，会不会是竖线太淡了没看清
> 2. 已解决
![SiYuan_iz2nWyG8i1](https://user-images.githubusercontent.com/27794098/159916399-1d67bbc1-262e-4412-9433-ce3d6488b4e8.gif)

思源笔记是微软应用商店1.9.2版，主题已经更到最新，两个问题依然存在，使用回车换行时，前面竖线会出现空隙，使用markdown的列表时，前面的竖线会消失
![image](https://user-images.githubusercontent.com/27794098/159917688-f8dfb5ec-6d9d-4a93-a048-86b504ab2766.png)
打开开发者工具，我看到原本引述前面的竖线样式被覆盖掉了，我加了`!important`显示出来了。作者主题竖线样式是加在这里，而列表项的class是list不是p，所以前面的竖线消失了
![image](https://user-images.githubusercontent.com/27794098/159918201-3f47ef3f-b104-43cc-b163-2b239381b3c8.png)

**Comment by zqhjl** [comment]
问题已解决，不过还没提交，等一下我把其他问题解决了再一起提交

**Comment by TracyIverson** [comment]
> 问题已解决，不过还没提交，等一下我把其他问题解决了再一起提交

原来是还没发布到集市，是我搞错了，辛苦作者了👍

**Comment by zqhjl** [comment]
该主题最新版本（v0.3.1）已解决，刚刚提交pr，要等等才能上集市。

你也可以直接在[本仓库](https://github.com/zqhjl/Rem-Craft/releases/download/0.3.1/Rem.Craft.zip)下载
