### ISSUE TITLE
右键菜单Bug

### ISSUE THREAD

**Issue by TracyIverson** [zqhjl/Rem-Craft#12]
二级菜单鼠标选中错误
![c1b1h-gzjar](https://user-images.githubusercontent.com/27794098/159830261-aa67ed9b-3a8f-43a3-a0a3-a6a9bd17bf4e.gif)

**Comment by zqhjl** [comment]
已解决

**Comment by zqhjl** [comment]
该主题最新版本（v0.3.1）已解决，刚刚提交pr，要等等才能上集市。

你也可以直接在[本仓库](https://github.com/zqhjl/Rem-Craft/releases/download/0.3.1/Rem.Craft.zip)下载
