### ISSUE TITLE
块菜单BUG

### ISSUE THREAD

**Issue by EberhardLin** [zqhjl/Rem-Craft#13]
如图所示：
![最新版本bug](https://user-images.githubusercontent.com/98400319/159877311-8fe84747-75f0-4638-af02-7ffd7cb87a45.gif)

测试了多个其他主题未发现该问题，表现为块菜单中有展开的内容鼠标无法正常移上去选取。

**Comment by zqhjl** [comment]
已经有人提出过并解决了

**Comment by EberhardLin** [comment]
该BUG是我在思源与主题都是最新版本下（思源1.9.4，主题我在集市看了没有弹出更新，今天更新过一次，应该是最新）依旧能够实现的，不知道是版本更新后导致的问题还是主题问题。
你看看你那里能够复现吗，新建表格-快菜单-复制/布局 鼠标能不能在浮现的子菜单里任意滑动选取，就像我的图片一样。

**Comment by zqhjl** [comment]
这个问题是今天刚刚解决的，还没有上传集市，要等等

**Comment by zqhjl** [comment]
该主题最新版本（v0.3.1）已解决，刚刚提交pr，要等等才能上集市。

你也可以直接在[本仓库](https://github.com/zqhjl/Rem-Craft/releases/download/0.3.1/Rem.Craft.zip)下载

**Comment by EberhardLin** [comment]
已解决，谢谢作者的辛苦付出。
