### ISSUE TITLE
块 菜单的二级菜单大概率无法使用

### ISSUE THREAD

**Issue by xgblack** [zqhjl/Rem-Craft#14]
![image](https://user-images.githubusercontent.com/30540766/160078854-dce1d3d1-225e-4703-8c2d-99aa4b039d76.png)
有一部分块，鼠标挡在一级菜单上二级菜单可以打开，但是当鼠标划到二级菜单上时，二级菜单就消失了。只有一小部分块可以使用二级菜单。
还有另一种情况，比如上图，鼠标可以放到二级菜单上，但是当我鼠标往下走，二级菜单就会变成 “复制”这一项的二级菜单里面去了
这种情况一般是什么原因造成的？

**Comment by zqhjl** [comment]
该主题最新版本（v0.3.1）已解决，刚刚提交pr，要等等才能上集市。

你也可以直接在[本仓库](https://github.com/zqhjl/Rem-Craft/releases/download/0.3.1/Rem.Craft.zip)下载
