### ISSUE TITLE
增加同步信息显示

### ISSUE THREAD

**Issue by EberhardLin** [zqhjl/Rem-Craft#16]
如图所示，在其他主题会显示当前同步状态：
![image](https://user-images.githubusercontent.com/98400319/160223371-8fc10cd9-06cb-49a4-a13b-b882787fff59.png)
而Rem Craft则不显示，**建议增加，让我们这些使用官方同步的人可以掌握同步情况**。
![image](https://user-images.githubusercontent.com/98400319/160223400-fafac83b-42e8-4814-b7ab-83a36efb0938.png)

**Comment by zqhjl** [comment]
已解决，下个版本更新
