### ISSUE TITLE
能出一个适合笔记本的嘛？

### ISSUE THREAD

**Issue by remoon1991** [zqhjl/Rem-Craft#3]
感觉间距太大了，尤其是侧栏和文档树，如果能间距小一点，更适合小屏幕一些。
小白一枚，根本不懂，想修改一下没修改明白。
百分感谢，或者文件中多一点注释，我打开发现一堆乱码，根据您写的提示也没弄明白。。。。
非程序猿，非CS，平时用R画个图啥的。。。
修改有注释的还行，没有注释现场歇菜

**Comment by zqhjl** [comment]
这个问题我也感觉到了，在我自己的工作电脑上就会显得大，在自己用的电脑上看上去又比较正常…

之后可能我会改成根据屏幕适配的，但是最近的话可能要先适应一下。

另外，根目录下的`theme.css`是编译后压缩过的文件，所以没有注释…需要你转到dev分支后，查看`src/styles`目录下的各scss文件，那里是有注释的。

过程确实比较复杂，不过对我个人来说，已经是能想到的最佳方案了…主要是为了将自用颜色变量和官方变量解耦的同时，还不影响软件使用

**Comment by remoon1991** [comment]
谢谢您，麻烦了，主要我真得不懂编程，用vscode也不太会设置。您看您有空把，谢谢！
祝好

发件人: Seven Chor
发送时间: 2021年12月31日 14:44
收件人: zqhjl/Rem-Craft
抄送: remoon1991; Author
主题: Re: [zqhjl/Rem-Craft] 能出一个适合笔记本的嘛？ (Issue #3)

这个问题我也感觉到了，在我自己的工作电脑上就会显得大，在自己用的电脑上看上去又比较正常…
之后可能我会改成根据屏幕适配的，但是最近的话可能要先适应一下。
另外，根目录下的theme.css是编译后压缩过的文件，所以没有注释…需要你转到dev分支后，查看src/styles目录下的各scss文件，那里是有注释的。
过程确实比较复杂，不过对我个人来说，已经是能想到的最佳方案了…主要是为了将自用颜色变量和官方变量解耦的同时，还不影响软件使用
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zqhjl** [comment]
您太客气了

**Comment by zqhjl** [comment]
已解决，当前解决方案为`min(12px, max(6.5px, 0.520vw * 6.5 / 8))`，即最小6.5px，最大12px，随屏幕宽度变化
