### ISSUE TITLE
文档树图标使用svg时不能正常居中

### ISSUE THREAD

**Issue by kuusei** [zqhjl/Rem-Craft#4]
问题描述:
文档树图标使用svg时不能正常居中

截图:
使用svg时
![image](https://user-images.githubusercontent.com/46283738/149867415-8078f581-5614-4e16-8cc7-6c3631b67e20.png)
使用emoji时
![image](https://user-images.githubusercontent.com/46283738/149867439-b5f25d9b-b5c3-42ff-8ae2-430277f41a7f.png)

**Comment by zqhjl** [comment]
请问文档树图标使用svg的方法是什么？我没有用过这一功能，不好意思
