### ISSUE TITLE
包含子文档的文档在文档树中与同级文档无法整齐排列

### ISSUE THREAD

**Issue by EberhardLin** [zqhjl/Rem-Craft#5]
如图:
![image](https://user-images.githubusercontent.com/98400319/150984044-f098d5c2-dd68-44ea-83b5-961f747700d4.png)

**Comment by zqhjl** [comment]
这个是主题特性，为了让文档树看起来更紧凑，之后删除竖线的话我会考虑改改

**Comment by EberhardLin** [comment]
> 

补充：
文档树可以通过这种形式
![image](https://user-images.githubusercontent.com/98400319/153554646-39812275-7768-4a92-a33f-addc7cbd8366.png)
一方面文档之间的父子级关系能更具有可识别性，另一方面也挺紧凑的；
但是说白了就是没啥改动，只是现主题版本的文档树设计实在是难以识别父子级关系，希望建议能被采纳：）

**Comment by zqhjl** [comment]
之后会在删除竖线的同时，改回原来的样式

**Comment by zqhjl** [comment]
已解决
