### ISSUE TITLE
块设置悬浮按钮的位置如何更为原来的呀

### ISSUE THREAD

**Issue by jiang66-so** [zqhjl/Rem-Craft#7]
![image](https://user-images.githubusercontent.com/59095088/153532543-25ba402d-2a14-41dd-ac2a-1a17966cd775.png)

**Comment by zqhjl** [comment]
额，我记得我没改过这个块标的位置

**Comment by EberhardLin** [comment]
刚想提这个问题，1.8.2版本后，块悬浮按钮位置出现问题。
还有鼠标光标的实际选取发生错位，我是错位到应显示位置的大右边（在编辑器里鼠标长按选取多个块即可发现选取区域在大右边）。

**Comment by EberhardLin** [comment]
> 我最近在养病，所以可能暂时没有精力维护了

抱歉，希望你能早日康复。

**Comment by zqhjl** [comment]
> 刚想提这个问题，1.8.2版本后，块悬浮按钮位置出现问题。 还有鼠标光标的实际选取发生错位，我是错位到应显示位置的大右边（在编辑器里鼠标长按选取多个块即可发现选取区域在大右边）。

这个问题没能复现，待会我更新版本后你可以再试试。

我个人觉得这个可能是小概率事件，下次如果碰到这种问题，可以用思源笔记自带的重置外观功能试试

**Comment by zqhjl** [comment]
已发现问题并解决
