### ISSUE TITLE
分屏后页面乱跳

### ISSUE THREAD

**Issue by JOYCELEEEEE** [zqhjl/Rem-Craft#8]
见 https://github.com/siyuan-note/siyuan/issues/4191#issue-1162266408

看到之前提的回复说在养病，祝安好。 期待修复的那天，craft主体真的很棒。

**Comment by zqhjl** [comment]
> 见 [siyuan-note/siyuan#4191 (comment)](https://github.com/siyuan-note/siyuan/issues/4191#issue-1162266408)
> 
> 看到之前提的回复说在养病，祝安好。 期待修复的那天，craft主体真的很棒。

谢谢，但是这个问题没能复现，待会我更新版本后你可以再试试。

我个人觉得这个可能是小概率事件，下次如果碰到这种问题，可以用思源笔记自带的重置外观功能试试。
